require 'coffee-script/register'
http = require('http')
express = require('express')
app = express()
mongoose = require('mongoose')
port = 3700
app.set 'views', __dirname + '/tpl'
app.set 'view engine', 'jade'
app.engine 'jade', require('jade').__express
app.use express.static(__dirname + '/public')
app.use require('connect-assets')()
mongoose.connect 'mongodb://localhost:27017/livelist'

Patient = mongoose.model('Patient',
  first_name: String
  last_name: String)

io = require('socket.io').listen(app.listen(port))

require('./routes') app, mongoose, Patient
require('./sockets') io, Patient

# app.listen(port);
console.log 'Listening on port ' + port

# ---
# generated by js2coffee 2.1.0