// Generated by CoffeeScript 1.9.3
(function() {
  
#= require vendor/jquery.js
#= require vendor/underscore.js
#= require vendor/backbone.js
#= require vendor/socket.io.js
;
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Sockets.Router = (function(superClass) {
    extend(Router, superClass);

    function Router() {
      return Router.__super__.constructor.apply(this, arguments);
    }

    Router.prototype.initialize = function() {
      this.patients = new Sockets.Patients;
      return Backbone.history.start();
    };

    Router.prototype.routes = {
      '': 'index'
    };

    Router.prototype.index = function() {
      return this.view = new Sockets.PatientList({
        collection: this.patients
      });
    };

    return Router;

  })(Backbone.Router);

  window.app = new Sockets.Router;

}).call(this);
