// Generated by CoffeeScript 1.9.3
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Sockets.Patient = (function(superClass) {
    extend(Patient, superClass);

    function Patient() {
      return Patient.__super__.constructor.apply(this, arguments);
    }

    Patient.prototype.idAttribute = "_id";

    Patient.prototype.defaults = {
      first_name: null,
      last_name: null
    };

    return Patient;

  })(Backbone.Model);

}).call(this);
