// Generated by CoffeeScript 1.9.3
(function() {
  var socket;

  socket = io.connect("http://localhost:3700");

  socket.on("patients", function(data) {
    return app.patients.reset(data);
  });

}).call(this);
